version: '3.8'

services:
  cloud-run-lab:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloud-run-lab
    ports:
      - "8080:8080"
    environment:
      - WEB_SERVER_PORT=:8080
    restart: unless-stopped
