version: '3.8'

services:
  cloud-run-lab:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloud-run-lab
    ports:
      - "8000:8000"
    environment:
      - WEB_SERVER_PORT=:8000
    restart: unless-stopped
